# Generated by Django 3.0.2 on 2020-03-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingPile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DMID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('installTime', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('gunNumber', models.CharField(max_length=200)),
                ('ratedPower', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('chargingRecord', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderContractAddress', models.CharField(max_length=200)),
                ('chargingPileDMID', models.CharField(max_length=200)),
                ('electricalVehicleDMID', models.CharField(max_length=200)),
                ('createTime', models.CharField(max_length=200)),
                ('endTime', models.CharField(max_length=200)),
                ('orderState', models.CharField(max_length=200)),
                ('chargingPower', models.CharField(max_length=200)),
                ('tokenNeeded', models.CharField(max_length=200)),
                ('tokenReceived', models.CharField(max_length=200)),
            ],
        ),
    ]
